'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useCollection, useFirestore, useMemoFirebase, useDoc } from '@/firebase';
import { collection, query, writeBatch, doc, deleteDoc } from 'firebase/firestore';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'; // Combined Card imports
import { MainPageHeader } from "@/components/page-header"; // Keep MainPageHeader import
import { Button } from '@/components/ui/button';
import { PlusCircle, Edit, Trash2, ChevronDown, WandSparkles, Loader2, ClipboardPaste, BookOpen, Layers, MoreHorizontal, AlertTriangle } from 'lucide-react'; // Consolidated Lucide imports
import { Skeleton } from '@/components/ui/skeleton';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { toast } from '@/hooks/use-toast';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertDialog, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'; // Consolidated AlertDialog imports

import { ChecklistTemplate } from '@/types/checklist'; // Assuming this is needed for Matrix generation
import { useAIChat } from '@/lib/ai-client'; // Assuming this is for AI features

interface MatrixItem {
    id: string;
    type: 'source' | 'objective';
    name: string;
    description: string;
    parentId?: string; // For objectives to link to sources
    linkedObjectives?: string[]; // For sources to list linked objectives
}

interface CoherenceMatrix {
    id: string;
    name: string;
    description: string;
    items: MatrixItem[];
    createdAt: Date;
    updatedAt: Date;
}

const NewMatrixItemDialog = ({ isOpen, setIsOpen, onSave, parentId, type, initialData, matrixId }: {
    isOpen: boolean;
    setIsOpen: (open: boolean) => void;
    onSave: (item: Partial<MatrixItem>) => Promise<void>;
    parentId?: string;
    type: 'source' | 'objective';
    initialData?: MatrixItem;
    matrixId: string;
}) => {
    const [name, setName] = useState(initialData?.name || '');
    const [description, setDescription] = useState(initialData?.description || '');
    const [loading, setLoading] = useState(false);
    const [aiLoading, setAiLoading] = useState(false);
    const firestore = useFirestore();
    const chat = useAIChat();

    const handleSave = async () => {
        setLoading(true);
        await onSave({ ...initialData, name, description, parentId, type });
        setLoading(false);
        setIsOpen(false);
        setName('');
        setDescription('');
    };

    const generateAIContent = useCallback(async () => {
        setAiLoading(true);
        try {
            const matrixDocRef = doc(firestore, 'coherenceMatrices', matrixId);
            const matrixDoc = await useDoc(matrixDocRef);
            const matrixData = matrixDoc.data() as CoherenceMatrix;

            if (!matrixData) {
                toast({
                    title: 'Error',
                    description: 'Could not fetch matrix data for AI generation.',
                    variant: 'destructive',
                });
                setAiLoading(false);
                return;
            }

            const prompt = `Generate a detailed description for a ${type} named "${name}" within the coherence matrix "${matrixData.name}" (Description: ${matrixData.description || 'N/A'}). If this is an objective, it is linked to source ID: ${parentId}.`;

            const response = await chat(prompt); // Assuming chat returns string
            setDescription(response);
            toast({
                title: 'AI Generated',
                description: `Description for "${name}" generated by AI.`,
            });
        } catch (error) {
            console.error('AI generation error:', error);
            toast({
                title: 'Error',
                description: 'Failed to generate AI content. Please try again.',
                variant: 'destructive',
            });
        } finally {
            setAiLoading(false);
        }
    }, [name, description, chat, firestore, type, matrixId, parentId]);


    return (
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogTrigger asChild>
                {/* Resolved: Keeping temp-save-work's Button styling as it seems like a UI improvement */}
                <Button variant="outline" size="sm" className="h-8 text-[10px] font-black uppercase gap-2 border-slate-300">
                    <PlusCircle className="h-4 w-4" /> Add {type === 'source' ? 'Source' : 'Objective'}
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>{initialData ? 'Edit' : 'Add New'} {type === 'source' ? 'Source' : 'Objective'}</DialogTitle>
                    <DialogDescription>
                        {initialData ? 'Edit the details of this item.' : `Add a new ${type === 'source' ? 'source document or standard' : 'objective'} to your coherence matrix.`}
                    </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="name" className="text-right">
                            Name
                        </Label>
                        <Input
                            id="name"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            className="col-span-3"
                            disabled={loading}
                        />
                    </div>
                    <div className="grid grid-cols-4 items-start gap-4">
                        <Label htmlFor="description" className="text-right">
                            Description
                        </Label>
                        <div className="col-span-3">
                            <Textarea
                                id="description"
                                value={description}
                                onChange={(e) => setDescription(e.target.value)}
                                className="min-h-[100px]"
                                disabled={loading}
                            />
                            <Button
                                variant="outline"
                                size="sm"
                                className="mt-2 text-xs gap-1"
                                onClick={generateAIContent}
                                disabled={aiLoading || loading || !name}
                            >
                                {aiLoading ? (
                                    <>
                                        <Loader2 className="mr-2 h-3 w-3 animate-spin" />
                                        Generating...
                                    </>
                                ) : (
                                    <>
                                        <WandSparkles className="h-3 w-3" /> Generate with AI
                                    </>
                                )}
                            </Button>
                        </div>
                    </div>
                </div>
                <DialogFooter>
                    <Button variant="outline" onClick={() => setIsOpen(false)} disabled={loading}>
                        Cancel
                    </Button>
                    <Button type="submit" onClick={handleSave} disabled={loading || !name}>
                        {loading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Saving...
                            </>
                        ) : (
                            'Save Changes'
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};

const NewMatrixDialog = ({ isOpen, setIsOpen, onSave, initialData }: {
    isOpen: boolean;
    setIsOpen: (open: boolean) => void;
    onSave: (matrix: Partial<CoherenceMatrix>) => Promise<void>;
    initialData?: CoherenceMatrix;
}) => {
    const [name, setName] = useState(initialData?.name || '');
    const [description, setDescription] = useState(initialData?.description || '');
    const [loading, setLoading] = useState(false);

    const handleSave = async () => {
        setLoading(true);
        await onSave({ ...initialData, name, description });
        setLoading(false);
        setIsOpen(false);
        setName('');
        setDescription('');
    };

    return (
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>{initialData ? 'Edit' : 'Create New'} Coherence Matrix</DialogTitle>
                    <DialogDescription>
                        {initialData ? 'Edit the details of this matrix.' : 'Create a new coherence matrix to define your safety structure.'}
                    </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="matrix-name" className="text-right">
                            Name
                        </Label>
                        <Input
                            id="matrix-name"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            className="col-span-3"
                            disabled={loading}
                        />
                    </div>
                    <div className="grid grid-cols-4 items-start gap-4">
                        <Label htmlFor="matrix-description" className="text-right">
                            Description
                        </Label>
                        <Textarea
                            id="matrix-description"
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            className="col-span-3 min-h-[100px]"
                            disabled={loading}
                        />
                    </div>
                </div>
                <DialogFooter>
                    <Button variant="outline" onClick={() => setIsOpen(false)} disabled={loading}>
                        Cancel
                    </Button>
                    <Button type="submit" onClick={handleSave} disabled={loading || !name}>
                        {loading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Saving...
                            </>
                        ) : (
                            'Save Matrix'
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};

const DeleteConfirmationDialog = ({ isOpen, setIsOpen, onDelete }: {
    isOpen: boolean;
    setIsOpen: (open: boolean) => void;
    onDelete: () => Promise<void>;
}) => {
    const [loading, setLoading] = useState(false);

    const handleDelete = async () => {
        setLoading(true);
        await onDelete();
        setLoading(false);
        setIsOpen(false);
    };

    return (
        <AlertDialog open={isOpen} onOpenChange={setIsOpen}>
            <AlertDialogContent>
                <AlertDialogHeader>
                    <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                    <AlertDialogDescription>
                        This action cannot be undone. This will permanently delete your selected item and all its associated objectives.
                    </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                    <Button variant="outline" onClick={() => setIsOpen(false)} disabled={loading}>
                        Cancel
                    </Button>
                    <Button variant="destructive" onClick={handleDelete} disabled={loading}>
                        {loading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Deleting...
                            </>
                        ) : (
                            'Delete'
                        )}
                    </Button>
                </DialogFooter>
            </AlertDialogContent>
        </AlertDialog>
    );
};

const LinkObjectivesDialog = ({ isOpen, setIsOpen, sourceId, matrixId, currentLinkedObjectives, onUpdateLinks }: {
    isOpen: boolean;
    setIsOpen: (open: boolean) => void;
    sourceId: string;
    matrixId: string;
    currentLinkedObjectives: string[];
    onUpdateLinks: (sourceId: string, newLinks: string[]) => Promise<void>;
}) => {
    const firestore = useFirestore();
    const objectivesCollectionRef = collection(firestore, 'coherenceMatrices', matrixId, 'items');
    const objectivesQuery = query(objectivesCollectionRef);
    const { data: allItems, isLoading } = useCollection<MatrixItem>(objectivesQuery);
    const [selectedObjectives, setSelectedObjectives] = useState<string[]>([]);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        setSelectedObjectives(currentLinkedObjectives);
    }, [currentLinkedObjectives, isOpen]);

    const availableObjectives = useMemo(() => {
        return allItems?.filter(item => item.type === 'objective') || [];
    }, [allItems]);

    const handleToggleObjective = (objectiveId: string) => {
        setSelectedObjectives(prev =>
            prev.includes(objectiveId)
                ? prev.filter(id => id !== objectiveId)
                : [...prev, objectiveId]
        );
    };

    const handleSaveLinks = async () => {
        setLoading(true);
        await onUpdateLinks(sourceId, selectedObjectives);
        setLoading(false);
        setIsOpen(false);
    };

    return (
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogContent className="sm:max-w-[480px]">
                <DialogHeader>
                    <DialogTitle>Link Objectives to Source</DialogTitle>
                    <DialogDescription>
                        Select the objectives that this source document or standard covers.
                    </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4 max-h-[400px] overflow-y-auto">
                    {isLoading ? (
                        <Skeleton className="h-40 w-full" />
                    ) : availableObjectives.length === 0 ? (
                        <p className="text-sm text-gray-500">No objectives available to link. Add some objectives first!</p>
                    ) : (
                        <div className="grid gap-2">
                            {availableObjectives.map(objective => (
                                <div key={objective.id} className="flex items-center space-x-2">
                                    <Checkbox
                                        id={`objective-${objective.id}`}
                                        checked={selectedObjectives.includes(objective.id)}
                                        onCheckedChange={() => handleToggleObjective(objective.id)}
                                        disabled={loading}
                                    />
                                    <Label htmlFor={`objective-${objective.id}`} className="font-normal">
                                        {objective.name}
                                    </Label>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
                <DialogFooter>
                    <Button variant="outline" onClick={() => setIsOpen(false)} disabled={loading}>
                        Cancel
                    </Button>
                    <Button type="submit" onClick={handleSaveLinks} disabled={loading}>
                        {loading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Saving...
                            </>
                        ) : (
                            'Save Links'
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};


// Main Page Component
export default function CoherenceMatrixPage() {
    const firestore = useFirestore();

    const matricesCollectionRef = collection(firestore, 'coherenceMatrices');
    const { data: matrices, isLoading: isLoadingMatrices, error: matricesError } = useCollection<CoherenceMatrix>(matricesCollectionRef);
    const [selectedMatrixId, setSelectedMatrixId] = useState<string | null>(null);

    const selectedMatrix = useMemo(() => {
        return matrices?.find(m => m.id === selectedMatrixId);
    }, [matrices, selectedMatrixId]);

    const itemsCollectionRef = selectedMatrixId ? collection(firestore, 'coherenceMatrices', selectedMatrixId, 'items') : null;
    const itemsQuery = itemsCollectionRef ? query(itemsCollectionRef) : null;
    const { data: allItems, isLoading: isLoadingItems, error: itemsError } = useCollection<MatrixItem>(itemsQuery);

    const sources = useMemo(() => {
        return allItems?.filter(item => item.type === 'source') || [];
    }, [allItems]);

    const objectives = useMemo(() => {
        return allItems?.filter(item => item.type === 'objective') || [];
    }, [allItems]);

    const [isNewMatrixDialogOpen, setIsNewMatrixDialogOpen] = useState(false);
    const [editingMatrix, setEditingMatrix] = useState<CoherenceMatrix | null>(null);

    const [isNewItemDialogOpen, setIsNewItemDialogOpen] = useState(false);
    const [editingItem, setEditingItem] = useState<MatrixItem | null>(null);
    const [newItemType, setNewItemType] = useState<'source' | 'objective'>('source');
    const [newItemParentId, setNewItemParentId] = useState<string | undefined>(undefined);

    const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
    const [itemToDelete, setItemToDelete] = useState<{ id: string; type: 'matrix' | 'item' } | null>(null);

    const [isLinkObjectivesDialogOpen, setIsLinkObjectivesDialogOpen] = useState(false);
    const [linkingSourceId, setLinkingSourceId] = useState<string | null>(null);
    const [currentLinkedObjectives, setCurrentLinkedObjectives] = useState<string[]>([]);

    useEffect(() => {
        if (!selectedMatrixId && matrices && matrices.length > 0) {
            setSelectedMatrixId(matrices[0].id);
        }
    }, [matrices, selectedMatrixId]);

    const handleCreateUpdateMatrix = async (matrixData: Partial<CoherenceMatrix>) => {
        try {
            if (matrixData.id) {
                // Update existing
                await writeBatch(firestore)
                    .update(doc(matricesCollectionRef, matrixData.id), {
                        name: matrixData.name,
                        description: matrixData.description,
                        updatedAt: new Date(),
                    })
                    .commit();
                toast({
                    title: 'Matrix Updated',
                    description: `Coherence matrix "${matrixData.name}" has been updated.`,
                });
            } else {
                // Create new
                const newDocRef = doc(matricesCollectionRef);
                await writeBatch(firestore)
                    .set(newDocRef, {
                        id: newDocRef.id,
                        name: matrixData.name,
                        description: matrixData.description,
                        createdAt: new Date(),
                        updatedAt: new Date(),
                        items: [], // Initialize with empty items array
                    })
                    .commit();
                toast({
                    title: 'Matrix Created',
                    description: `New coherence matrix "${matrixData.name}" has been created.`,
                });
            }
        } catch (error) {
            console.error('Error creating/updating matrix:', error);
            toast({
                title: 'Error',
                description: `Failed to ${matrixData.id ? 'update' : 'create'} matrix.`,
                variant: 'destructive',
            });
        }
    };

    const handleDeleteMatrix = async () => {
        if (!itemToDelete || itemToDelete.type !== 'matrix' || !selectedMatrixId) return;
        try {
            await deleteDoc(doc(matricesCollectionRef, itemToDelete.id));
            toast({
                title: 'Matrix Deleted',
                description: 'The coherence matrix and all its items have been deleted.',
            });
            setSelectedMatrixId(null); // Deselect after deletion
        } catch (error) {
            console.error('Error deleting matrix:', error);
            toast({
                title: 'Error',
                description: 'Failed to delete matrix.',
                variant: 'destructive',
            });
        }
    };

    const handleCreateUpdateItem = async (itemData: Partial<MatrixItem>) => {
        if (!selectedMatrixId) return;
        try {
            const itemsRef = collection(firestore, 'coherenceMatrices', selectedMatrixId, 'items');
            if (itemData.id) {
                // Update existing item
                await writeBatch(firestore)
                    .update(doc(itemsRef, itemData.id), {
                        name: itemData.name,
                        description: itemData.description,
                        parentId: itemData.parentId,
                        type: itemData.type,
                    })
                    .commit();
                toast({
                    title: 'Item Updated',
                    description: `${itemData.type === 'source' ? 'Source' : 'Objective'} "${itemData.name}" has been updated.`,
                });
            } else {
                // Create new item
                const newDocRef = doc(itemsRef);
                await writeBatch(firestore)
                    .set(newDocRef, {
                        id: newDocRef.id,
                        name: itemData.name,
                        description: itemData.description,
                        type: itemData.type,
                        parentId: itemData.parentId || null,
                        linkedObjectives: itemData.type === 'source' ? [] : undefined, // Only sources have linkedObjectives
                    })
                    .commit();
                toast({
                    title: 'Item Created',
                    description: `New ${itemData.type === 'source' ? 'source' : 'objective'} "${itemData.name}" has been created.`,
                });
            }
        } catch (error) {
            console.error('Error creating/updating item:', error);
            toast({
                title: 'Error',
                description: `Failed to ${itemData.id ? 'update' : 'create'} item.`,
                variant: 'destructive',
            });
        }
    };

    const handleDeleteItem = async () => {
        if (!itemToDelete || itemToDelete.type !== 'item' || !selectedMatrixId) return;
        try {
            const itemsRef = collection(firestore, 'coherenceMatrices', selectedMatrixId, 'items');
            await deleteDoc(doc(itemsRef, itemToDelete.id));
            toast({
                title: 'Item Deleted',
                description: 'The selected item has been deleted.',
            });
        } catch (error) {
            console.error('Error deleting item:', error);
            toast({
                title: 'Error',
                description: 'Failed to delete item.',
                variant: 'destructive',
            });
        }
    };

    const handleUpdateSourceLinks = async (sourceId: string, newLinks: string[]) => {
        if (!selectedMatrixId) return;
        try {
            const sourceDocRef = doc(firestore, 'coherenceMatrices', selectedMatrixId, 'items', sourceId);
            await writeBatch(firestore)
                .update(sourceDocRef, { linkedObjectives: newLinks })
                .commit();
            toast({
                title: 'Links Updated',
                description: 'Source document links have been updated.',
            });
        } catch (error) {
            console.error('Error updating source links:', error);
            toast({
                title: 'Error',
                description: 'Failed to update source links.',
                variant: 'destructive',
            });
        }
    };

    if (isLoadingMatrices) {
        return (
            <div className="flex flex-col gap-6 p-6">
                <Skeleton className="h-10 w-64" />
                <Skeleton className="h-80 w-full" />
            </div>
        );
    }

    if (matricesError) {
        return <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Error loading matrices: {matricesError.message}</AlertDescription>
        </Alert>;
    }

    return (
        <div className="flex flex-col space-y-6 p-6">
            {/* Resolved: Using MainPageHeader component */}
            <MainPageHeader
                title="Coherence Matrix"
                description="Manage your safety coherence matrix, linking sources to objectives."
                actions={
                    <div className="flex gap-2">
                        <NewMatrixDialog
                            isOpen={isNewMatrixDialogOpen}
                            setIsOpen={setIsNewMatrixDialogOpen}
                            onSave={handleCreateUpdateMatrix}
                            initialData={editingMatrix || undefined}
                        />
                        <Button
                            onClick={() => {
                                setEditingMatrix(null);
                                setIsNewMatrixDialogOpen(true);
                            }}
                        >
                            <PlusCircle className="mr-2 h-4 w-4" /> Create Matrix
                        </Button>
                    </div>
                }
            />

            {matrices && matrices.length > 0 && (
                <div className="flex items-center gap-4">
                    <Label htmlFor="select-matrix" className="shrink-0">Select Matrix:</Label>
                    <Select value={selectedMatrixId || ''} onValueChange={setSelectedMatrixId}>
                        <SelectTrigger id="select-matrix" className="w-[300px]">
                            <SelectValue placeholder="Select a Coherence Matrix" />
                        </SelectTrigger>
                        <SelectContent>
                            {matrices.map(matrix => (
                                <SelectItem key={matrix.id} value={matrix.id}>{matrix.name}</SelectItem>
                            ))}
                        </SelectContent>
                    </Select>
                    {selectedMatrix && (
                        <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                                <Button variant="outline" size="sm" className="gap-2">
                                    <Edit className="h-4 w-4" /> Manage Matrix <ChevronDown className="h-4 w-4" />
                                </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent>
                                <DropdownMenuItem onClick={() => { setEditingMatrix(selectedMatrix); setIsNewMatrixDialogOpen(true); }}>
                                    <Edit className="mr-2 h-4 w-4" /> Edit Matrix
                                </DropdownMenuItem>
                                <DropdownMenuSeparator />
                                <DropdownMenuItem
                                    className="text-red-600"
                                    onClick={() => {
                                        setItemToDelete({ id: selectedMatrix.id, type: 'matrix' });
                                        setIsDeleteDialogOpen(true);
                                    }}
                                >
                                    <Trash2 className="mr-2 h-4 w-4" /> Delete Matrix
                                </DropdownMenuItem>
                            </DropdownMenuContent>
                        </DropdownMenu>
                    )}
                </div>
            )}

            {!selectedMatrixId ? (
                <div className="flex flex-col items-center justify-center p-10 border rounded-lg bg-white dark:bg-gray-800">
                    <p className="text-lg text-gray-600 dark:text-gray-400">
                        {matrices && matrices.length === 0
                            ? "No coherence matrices found. Create one to get started!"
                            : "Please select a coherence matrix to view its items."}
                    </p>
                    {matrices && matrices.length === 0 && (
                        <Button className="mt-4" onClick={() => {
                            setEditingMatrix(null);
                            setIsNewMatrixDialogOpen(true);
                        }}>
                            <PlusCircle className="mr-2 h-4 w-4" /> Create First Matrix
                        </Button>
                    )}
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Sources Column */}
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">Sources (Documents & Standards)</CardTitle>
                            {/* NewMatrixItemDialog is already handling the button inside DialogTrigger */}
                            <NewMatrixItemDialog
                                isOpen={isNewItemDialogOpen && newItemType === 'source'}
                                setIsOpen={setIsNewItemDialogOpen}
                                onSave={handleCreateUpdateItem}
                                type="source"
                                initialData={editingItem || undefined}
                                matrixId={selectedMatrixId}
                            />
                        </CardHeader>
                        <CardContent>
                            {isLoadingItems ? (
                                <Skeleton className="h-40 w-full" />
                            ) : sources.length === 0 ? (
                                <p className="text-sm text-gray-500">No sources added yet.</p>
                            ) : (
                                <div className="space-y-4">
                                    {sources.map(source => (
                                        <div key={source.id} className="border p-4 rounded-md shadow-sm bg-white dark:bg-gray-700">
                                            <div className="flex items-center justify-between mb-2">
                                                <h3 className="font-bold text-lg">{source.name}</h3>
                                                <DropdownMenu>
                                                    <DropdownMenuTrigger asChild>
                                                        <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                                            <span className="sr-only">Open menu</span>
                                                            <MoreHorizontal className="h-4 w-4" />
                                                        </Button>
                                                    </DropdownMenuTrigger>
                                                    <DropdownMenuContent align="end">
                                                        <DropdownMenuItem onClick={() => {
                                                            setEditingItem(source);
                                                            setNewItemType('source');
                                                            setIsNewItemDialogOpen(true);
                                                        }}>
                                                            <Edit className="mr-2 h-4 w-4" /> Edit
                                                        </DropdownMenuItem>
                                                        <DropdownMenuItem onClick={() => {
                                                            setLinkingSourceId(source.id);
                                                            setCurrentLinkedObjectives(source.linkedObjectives || []);
                                                            setIsLinkObjectivesDialogOpen(true);
                                                        }}>
                                                            <Layers className="mr-2 h-4 w-4" /> Link Objectives
                                                        </DropdownMenuItem>
                                                        <DropdownMenuSeparator />
                                                        <DropdownMenuItem
                                                            className="text-red-600"
                                                            onClick={() => {
                                                                setItemToDelete({ id: source.id, type: 'item' });
                                                                setIsDeleteDialogOpen(true);
                                                            }}
                                                        >
                                                            <Trash2 className="mr-2 h-4 w-4" /> Delete
                                                        </DropdownMenuItem>
                                                    </DropdownMenuContent>
                                                </DropdownMenu>
                                            </div>
                                            <p className="text-sm text-gray-600 dark:text-gray-300">{source.description}</p>
                                            {source.linkedObjectives && source.linkedObjectives.length > 0 && (
                                                <div className="mt-3">
                                                    <h4 className="text-sm font-semibold mb-1">Linked Objectives:</h4>
                                                    <div className="flex flex-wrap gap-2">
                                                        {source.linkedObjectives.map(objId => {
                                                            const linkedObj = objectives.find(obj => obj.id === objId);
                                                            return linkedObj ? (
                                                                <Badge key={objId} variant="secondary" className="px-2 py-1 text-xs">
                                                                    {linkedObj.name}
                                                                </Badge>
                                                            ) : null;
                                                        })}
                                                    </div>
                                                </div>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            )}
                        </CardContent>
                    </Card>

                    {/* Objectives Column */}
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">Objectives</CardTitle>
                             {/* NewMatrixItemDialog is already handling the button inside DialogTrigger */}
                            <NewMatrixItemDialog
                                isOpen={isNewItemDialogOpen && newItemType === 'objective'}
                                setIsOpen={setIsNewItemDialogOpen}
                                onSave={handleCreateUpdateItem}
                                type="objective"
                                initialData={editingItem || undefined}
                                parentId={newItemParentId}
                                matrixId={selectedMatrixId}
                            />
                        </CardHeader>
                        <CardContent>
                            {isLoadingItems ? (
                                <Skeleton className="h-40 w-full" />
                            ) : objectives.length === 0 ? (
                                <p className="text-sm text-gray-500">No objectives added yet.</p>
                            ) : (
                                <div className="space-y-4">
                                    {objectives.map(objective => (
                                        <div key={objective.id} className="border p-4 rounded-md shadow-sm bg-white dark:bg-gray-700">
                                            <div className="flex items-center justify-between mb-2">
                                                <h3 className="font-bold text-lg">{objective.name}</h3>
                                                <DropdownMenu>
                                                    <DropdownMenuTrigger asChild>
                                                        <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                                            <span className="sr-only">Open menu</span>
                                                            <MoreHorizontal className="h-4 w-4" />
                                                        </Button>
                                                    </DropdownMenuTrigger>
                                                    <DropdownMenuContent align="end">
                                                        <DropdownMenuItem onClick={() => {
                                                            setEditingItem(objective);
                                                            setNewItemType('objective');
                                                            setIsNewItemDialogOpen(true);
                                                        }}>
                                                            <Edit className="mr-2 h-4 w-4" /> Edit
                                                        </DropdownMenuItem>
                                                        <DropdownMenuSeparator />
                                                        <DropdownMenuItem
                                                            className="text-red-600"
                                                            onClick={() => {
                                                                setItemToDelete({ id: objective.id, type: 'item' });
                                                                setIsDeleteDialogOpen(true);
                                                            }}
                                                        >
                                                            <Trash2 className="mr-2 h-4 w-4" /> Delete
                                                        </DropdownMenuItem>
                                                    </DropdownMenuContent>
                                                </DropdownMenu>
                                            </div>
                                            <p className="text-sm text-gray-600 dark:text-gray-300">{objective.description}</p>
                                            {objective.parentId && (
                                                <p className="text-xs text-gray-500 mt-2">
                                                    Linked to Source: {sources.find(s => s.id === objective.parentId)?.name || 'N/A'}
                                                </p>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            )}
                        </CardContent>
                    </Card>
                </div>
            )}

            <DeleteConfirmationDialog
                isOpen={isDeleteDialogOpen}
                setIsOpen={setIsDeleteDialogOpen}
                onDelete={itemToDelete?.type === 'matrix' ? handleDeleteMatrix : handleDeleteItem}
            />

            {linkingSourceId && (
                <LinkObjectivesDialog
                    isOpen={isLinkObjectivesDialogOpen}
                    setIsOpen={setIsLinkObjectivesDialogOpen}
                    sourceId={linkingSourceId}
                    matrixId={selectedMatrixId!}
                    currentLinkedObjectives={currentLinkedObjectives}
                    onUpdateLinks={handleUpdateSourceLinks}
                />
            )}
        </div>
    );
}
